config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  post 'pages/direccion'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def direccion
		if params[:latitude].present? && params[:longitude].present?
			@direccion = Geocoder.address([params[:latitude],params[:longitude]])
		else
			@direccion = "error"
		end
		respond_to do |format|
			format.js
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geolocation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/direccion.js.erb
$("#direccion").html("<%= @direccion %>");

app/views/pages/index.html.erb
<!-- <h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
-->
<div id="demo"> </div>

<ul>
	<li> <%= link_to 'direccion',pages_direccion_path %></li>
</ul>

<div id="latitud"></div>
<div id="longitud"></div>

<button onclick="getLocation()">Try It</button>

<div><p>la direccion corresponde a :<span id="direccion"></span></p> </div>

<script>
	var x = document.getElementById("latitud");
	var y = document.getElementById("longitud");
	function getLocation() {
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(showPosition);
		} else {
			x.innerHTML = "Geolocation is not supported by this browser.";
		}
	}

	function showPosition(position) {
		x.innerHTML = "Latitude: " + position.coords.latitude;
		y.innerHTML = "Longitude: " + position.coords.longitude;

		$.ajax({
			url: '<%= pages_direccion_path %>',
			type: 'POST',
			dataType: 'script',
			data: {
				latitude: position.coords.latitude,
				longitude: position.coords.longitude
			},
		});


	}


</script>